version: '3.8'

services:
  app:
    build: .
    container_name: gamestore_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=gamestore
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gamestore_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=gamestore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
